const postsTypes = {
  GET_POSTS: 'GET_POSTS',
  GET_POSTS_START: 'GET_POSTS_START',
  LIKE_POST: 'LIKE_POST',
  UNLIKE_POST: 'UNLIKE_POST',
  LIKE_COMMENT: 'LIKE_COMMENT',
  UNLIKE_COMMENT: 'UNLIKE_COMMENT'
};

export default postsTypes;
